# Package ######################################################################

[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "posggym_baselines"
description = "Implementations of planning and reinforcement learning algorithms for POSGGym environments."
readme = "README.md"
requires-python = ">= 3.8"
authors = [
    { name = "Jonathon Schwartz", email = "jonathon.schwartz@anu.edu.au" },
]
license = { text = "MIT License" }
keywords = [
    "multiagent-systems",
    "reinforcement-learning",
    "planning",
    "gymnasium",
    "POSG",
]
classifiers = [
    # change to `5 - Production/Stable` maybe one day
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    'Intended Audience :: Science/Research',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
]
dependencies = [
    "posggym[agents] >=0.5.0",
    "numpy >=1.21.0",
    "torch >=2.0.0",
    "wandb >=0.15",
    "tensorboard >=2.13.0",
    "matplotlib >=3.7.1",
    "seaborn >=0.12.2",
    "psutil >=5.9.0",
    "gymnasium ==0.29.1",
]
dynamic = ["version"]

[project.optional-dependencies]
# dependencies for baseline experiments
exps = ["pandas >=1.0", "pyyaml"]

[project.urls]
Homepage = "https://github.com/RDLLab/posggym-baselines"
Repository = "https://github.com/RDLLab/posggym-baselines"

[tool.setuptools.packages.find]
include = ["posggym_baselines", "posggym_baselines.*"]

[tool.setuptools.package-data]
rcpd = ["py.typed"]

# Linters and Test tools #######################################################
[tool.ruff]
# https://beta.ruff.rs/docs/settings/
src = ["posggym_baselines", "tests"]
show-fixes = true
# Same as Black.
line-length = 88
# Assume Python 3.10
target-version = "py310"

[tool.ruff.lint]
extend-select = ["C4", "SIM", "TCH"]

ignore = [
    "A001", "A002",
    "ARG001", "ARG002",
    "FBT001", "FBT002", "FBT003",
    "N802", "N806", "N812",
    "PGH003", "PGH004",
    "PLR2004", "C901", "RUF009", "NPY002", "B028",
    "S101", "S202", "S301", "S310", "S311",
	"T201", "T203"
]

select = [
    "A",
    "ARG",
    "B",
    "C4",
    "C90",
    "E",
    "ERA",
    "F",
    "FBT",
    "ICN",
    "I",
    "ISC",
    "N",
    "NPY",
    "PD",
    "PGH",
    "PIE",
    "PLE",
    "PLR",
    "Q",
    "RUF",
    "S",
    "SIM",
    "T",
    "UP",
    "W",
]


# Ignore `F401` (import violations) in all `__init__.py` files,
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "E402"]

[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.lint.isort]
lines-after-imports = 2
extra-standard-library = ["typing_extensions"]

[tool.ruff.lint.pylint]
max-statements = 100
max-branches=20
max-args=15


[tool.pyright]
include = ["porl/**"]
exclude = ["**/__pycache__"]
strict = []

typeCheckingMode = "basic"
pythonVersion = "3.10"
pythonPlatform = "All"
typeshedPath = "typeshed"
enableTypeIgnoreComments = true

# This is required as the CI pre-commit does not download the module
# (i.e. numpy, pygame, box2d). Therefore, we have to ignore missing imports
reportMissingImports = "none"
# Some modules are missing type stubs, which is an issue when running pyright locally
reportMissingTypeStubs = false
reportInvalidTypeVarUse = "none"
reportGeneralTypeIssues = "none"
reportUntypedFunctionDecorator = "none"
reportPrivateImportUsage = "none"
reportPrivateUsage = "warning"
reportUnboundVariable = "warning"
# this leads to lots of annoying errors
reportAttributeAccessIssue = "none"
reportArgumentType = "none"
